#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PGUSER=deploy
export EDITOR=/usr/local/bin/vim
export NODE_PATH=/usr/local/lib/node:$NODE_PATH
export PATH=~/bin:$PATH

alias gst="git status"
alias gb="git branch"
alias rst="touch tmp/restart.txt"
alias ta="tmux attach-session -t "
alias tn="tmux new -s "
alias cwip="bin/cucumber -p wip"

# cd to the top level git dir
a() {
  cd `git rev-parse --show-toplevel`
}

source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
